- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
- name: Installing necessary softwares
  apt: name="{{ item }}" state=present
  loop:
    - vim
    - yum-utils
    - certbot
    - python2-certbot-apache
    - mod_ssl